name: Host On Heroku

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 

        with:

          region: "us"

          branch: "master"

          usedocker: true

          stack: "container"

          heroku_api_key: ${{d2339a56-27f9-4066-826a-877ca99193de}}
          heroku_app_name: ${{darks8ulmybot}}
          heroku_email: ${{chumtungli@gmail.com}}

          docker_heroku_process_type: worker
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
