name: Host On Heroku

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 

        with:

          region: "us"

          branch: "master"

          usedocker: true

          stack: "container"

          heroku_api_key: ${{c76c4062-a463-4c3f-a109-c1de182ce22b}}
          heroku_app_name: ${{mirror5673525}}
          heroku_email: ${{naveen72461@gmail.com}}

          docker_heroku_process_type: worker
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
